site_name: memecomplete
site_description: Desktop client for https://memecomplete.com.
site_author: Jace Browning
repo_url: https://github.com/jacebrowning/memecomplete-desktop

theme: readthedocs

pages:
- Home: index.md
- About:
  - Release Notes: about/changelog.md
  - Contributing: about/contributing.md
  - License: about/license.md
