site_name: memegen
site_description: Desktop client for https://memegen.link.
site_author: Jace Browning
repo_url: https://github.com/jacebrowning/memegen-desktop

theme: readthedocs

pages:
- Home: index.md
- About:
  - Release Notes: about/changelog.md
  - Contributing: about/contributing.md
  - License: about/license.md
